server:
  port: ${PORT:0}

spring:
  application:
    name: items-service

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    io.micrometer.tracing: DEBUG
    org.springframework.web: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

config:
  baseurl:
    endpoint:
      products-service: http://products-service
