spring:
  application:
    name: msvc-mailsend
  config:
    import:
      optional:configserver:http://localhost:8888
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB