server:
  port: 8086

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8085

admin-paths:
  paths:
    -
      uri: "/usuarios"
      method: "POST"